import { StyleSheet } from "react-native";

export const VoiceSphereStyles = StyleSheet.create({
    container: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sphereContainer: {
    width: 280,
    height: 280,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sphere: {
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#0a4a8a',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#00d4ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 30,
    elevation: 20,
  },
  innerGlow: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: '#1565c0',
    shadowColor: '#4fc3f7',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 40,
  },
  highlight: {
    position: 'absolute',
    top: 30,
    left: 40,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#64b5f6',
    opacity: 0.4,
  },
  outerGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 2,
    borderColor: '#00d4ff',
    opacity: 0.3,
  },
  ripple: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 3,
    borderColor: '#00d4ff',
  },
  particle: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00d4ff',
  },
  statusText: {
    marginTop: 60,
    fontSize: 24,
    color: '#00d4ff',
    fontWeight: '600',
  },
  hintText: {
    marginTop: 12,
    fontSize: 14,
    color: '#666',
  },
});
